[options]
; Cấu hình cơ bản
addons_path = ./addons, ./custom
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
http_port = 8069

; Chế độ development
dev_mode = True
log_level = debug