{
    "name": "Hospital Management",
    "version": "1.0",
    "summary": "Hospital Management Software",
    "description": """Hospital Management Software""",
    "author": "ThaiDTC_Dev",
    "website": "",
    "category": "Productivity",
    "depends": ["base", "sale", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/data.xml",
        "wizard/create_appointment.xml",
        "wizard/search_appointment.xml",
        "views/patient.xml",
        "views/patient_kid.xml",
        "views/patient_gender.xml",
        "views/doctor.xml",
        "views/appointment.xml",
        "views/sale.xml",
        "views/partner.xml",
        "report/patient_details_template.xml",
        "report/patient_card_template.xml",
        "report/report.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
