{
    "name": "Hospital Management",
    "version": "1.0",
    "summary": "Hospital Management Software",
    "description": """Hospital Management Software""",
    "author": "ThaiDTC_Dev",
    "website": "",
    "category": "Productivity",
    "depends": ["base", "sale", "mail"],
    "data": ["security/ir.model.access.csv", "views/patient.xml", "views/sale.xml"],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
